### ISSUE TITLE
make input ondemand

### ISSUE THREAD

**Issue by Myr4ik** [marakew/AvProxy#1]
Hello!
When are you planning on implementing "input ondemand"?
I am a "home" user and alas, I do not have the opportunity to constantly receive all the streams ...

**Comment by marakew** [comment]
there is no deadline 
as i mention [https://cesbo.com/forum/topic/2161-avproxy/?page=15&tab=comments#comment-42623](url) i have prio to webrtc/rtsp/dvb and commercialization of product

**Comment by AlexanderHindos** [comment]
Can you make some instruction to install?

**Comment by AlexanderHindos** [comment]
Can I ask what type of output is it from AvProxy? Thanks in advance.

št 7. 5. 2020 o 16:37 John Doe <notifications@github.com> napísal(a):

**Comment by marakew** [comment]
all types of outputs described in readme
and this issue closed
i dont think topic started whish to receive any notify about it
