### ISSUE TITLE
Multiple proxy input programs do not perform work

### ISSUE THREAD

**Issue by SinLT** [marakew/AvProxy#3]
system：openwrt
![image](https://user-images.githubusercontent.com/20736404/112982621-42ae4480-918f-11eb-94f0-42a897e8e4d1.png)
![image](https://user-images.githubusercontent.com/20736404/112982738-65d8f400-918f-11eb-9cba-c5581bd4828e.png)
Only when there is only one proxy can the execution succeed, and then the proxy IP will succeed
Do you know what it is? Thank you very much

**Comment by marakew** [comment]
did you mean more then one inputs doest work ?
can you show log with one source ?

**Comment by SinLT** [comment]
![image](https://user-images.githubusercontent.com/20736404/113071869-3dd1ab00-91f8-11eb-94f9-9119bea8d645.png)
![image](https://user-images.githubusercontent.com/20736404/113071842-2f838f00-91f8-11eb-9592-f8137eb15071.png)
After the system is powered on, an agent can be executed successfully, followed by an agent
![image](https://user-images.githubusercontent.com/20736404/113072017-8b4e1800-91f8-11eb-89b1-94fc2baaef51.png)
![image](https://user-images.githubusercontent.com/20736404/113072037-9c972480-91f8-11eb-958f-d353b20e7484.png)
If the first execution of the system is multiple agents, it cannot be executed successfully

**Comment by marakew** [comment]
its very strange
i think this is not avproxy issue
may be openwrt ....
try look at order of starting services on openwrt
