### ISSUE TITLE
please help with ApplePreroll=N

### ISSUE THREAD

**Issue by lukiyz333** [marakew/AvProxy#4]
ApplePreroll=N is not working properly for me
I specified ApplePreroll=10 in AvProxy.xml and there are still only 3 segments in the output playlist

Example of AvProxy.xml:
<Input ApplePreroll=10 Url="http://10.10.10.252:1234/stream/channelid/771332855?profile=pass">
     <Output Name="One"/>

**Comment by marakew** [comment]
show your xml config
what version arch of binary are you trying

**Comment by lukiyz333** [comment]
<?xml version="1.0"?>
<AvProxy Ver="1">

<Input ApplePreroll=10 Url="http://10.10.10.252:1234/stream/channelid/771332855?profile=pass">
    <Output Name="One" Pnr=1/>
</Input>

I'm using version 2.19

**Comment by lukiyz333** [comment]
it doesn't work for me to paste the configuration part here

**Comment by marakew** [comment]
provide full name binary of avproxy

**Comment by marakew** [comment]
any way try using ApplePreroll param at Output section instead Input

**Comment by lukiyz333** [comment]
I use AvProxy-x64

<?xml version="1.0"?>
<AvProxy Ver="1">

<Input ApplePreroll=10 Url="
http://10.10.10.252:1234/stream/channelid/771332855?profile=pass">
    <Output Name="One" Pnr=1/>
</Input>

</AvProxy>


I noticed that AvProxy generates individual .ts files on the output in
different time lengths from 5-6s to 10s
Is it possible to set all .ts files to about 10 seconds?
It very often happens to me that after starting the playlist in the
SmartIPTV application, the sound does not go to the TV, but only the image.
I change the channel a few times before the sound starts
When I record an mpegts channel using ffmpeg, I get exactly 10 second .ts
files output and no audio error.
Is it possible to fix this somehow, or wouldn't updating to a newer version
of AvProxy solve it?
I really like the AvProxy utility in its simplicity, but unfortunately I
have these few problems.
Thanks for any advice.

čt 23. 2. 2023 v 16:38 odesílatel John Doe ***@***.***>
napsal:

**Comment by marakew** [comment]
you have correct xml config
and ApplePreroll options must work ok

can you show AvProxy-x64 -Trace output ?

this version tested
and works with ApplePreroll=10
got 10 segments 

[AvProxy]       Build=[Jan 31 2019 18:20:39 (host_x64.r1)]
[Main]  Build=[Jan 31 2019 18:21:29 (host_x64.r1)]
[BaseLib]       Build=[Jan 31 2019 18:21:29 (host_x64.r1)]

about less then 10 sec segment
can you check what segment byte size ?
avproxy split possible segment if segment 
1) input stream has discontinue
2) over ~8 Mb

**Comment by lukiyz333** [comment]
ApplePreroll=10 still doesn't work for me. I still only see 3x .ts files in
playlist.m3u8
but I'm more angry about the sound problem
would it be possible to upgrade to a newer version of AvProxy-x64?

the faulty .ts file that shows errors in the player was 6 seconds long and
8MB in size.

Dňa so 25. 2. 2023, 13:37 John Doe ***@***.***> napísal(a):

**Comment by marakew** [comment]
[AvProxy-x64.zip](https://github.com/marakew/AvProxy/files/10831765/AvProxy-x64.zip)
try this file, just download and remove zip extension, its normal ELF, check by console "file AvProxy-x64.zip"

1) segment size increased by 2, so as less 0x1000000 segment passed
2) ApplePreroll by default 10

if doest work, you have something wrong with your environment

**Comment by lukiyz333** [comment]
Yes. Now it's cool and I have 10x ts files in the playlist. ApplePreroll=10
works.
Is it possible to set ApplePreroll to 6?
But I still have the occasional problem with corrupted ts files
There are small black holes in the player.

If I record the same channel via ffmpeg, I don't see this "black hole"
problem.

Do you think upgrading to AvProxy 2.24 would help?
Thanks

**Comment by marakew** [comment]
well ApplePreroll=N fixed, i will update it later

can you share one .ts segment from AvProxy or share you input source for research about  size of .ts segment
i never saw size of ts segment more then 5Mb
may be possible issue in avproxy
any privacy info may send to email from readme of avproxy

no 2.24 include only rtsp input and some little fixes
btw iam will rewrite full mpegts muxer logic, so no sense for right now for upgrading
