### ISSUE TITLE
UDP output

### ISSUE THREAD

**Issue by pimboli** [marakew/AvProxy#7]
Hi, 
I am trying to use HLS input and publish this to UDP, but does not work.

```
<?xml version="1.0"?>
<AvProxy Ver="1">
<Input Url="m3u8://transcoder.xxx.stream/euronews-en/video.m3u8">
        <Output Name="udp1">
                <TsPush Url="udp://239.0.0.1:8888"/>
        </Output>
</Input>
</AvProxy>

```
Does anyone have an idea what I am doing wrong?

thanks

**Comment by marakew** [comment]
hello
show logging info

**Comment by pimboli** [comment]
`sven@sven-Standard-PC-i440FX-PIIX-1996:~/AvProxy$ sudo ./AvProxy-x64 -Trace
[AvProxy]       Build=[Mar  1 2023 01:29:34 (host_x64.r1)]
[Main]  Build=[Mar  1 2023 02:10:30 (host_x64.r1)]
[BaseLib]       Build=[Mar  1 2023 02:10:30 (host_x64.r1)]
[Arg 0-0]       [./AvProxy-x64]
[Arg 1-1]       [-Trace]
[NetLib]        Host=sven-Standard-PC-i440FX-PIIX-1996
[NetLib]        IFace=lo        Ip=[127.0.0.1]
[NetLib]        IFace=ens18     Ip=[192.168.0.131]
[NetLib]        IFace=lo        Mac=[00:00:00:00:00:00]
[NetLib]        IFace=ens18     Mac=[1E:95:6D:E6:E9:6A]
[HttpServer]    Build=[Mar  1 2023 01:32:00 (host_x64.r1)]
[HttpServer]    [Open] Tcp=45365
[AvProxy]       Url is invalid, use local configuration file [AvProxy.xml]
[TaskThread]    [52222] Began operating
[AvProxy]       Synchronization XML [0 -> 1]
[AvProxy]       Open Input=[https://transcoder.xxx.stream/euronews-en/mpegts]
Update Output...
Open Output=udp1
Output: Name udp1, Desc udp1, Pnr -1, Apple(AES128 0, Reserve 1, Preroll 3)
[HttpClient]    Build=[Mar  1 2023 01:31:32 (host_x64.r1)]
[HttpClient]    [7]     Resolve [transcoder.xxx.stream]
[DnsThread]     [52227] Began operating
[Signal]        Build=[Mar  1 2023 01:29:41 (host_x64.r1)]
[Signal]        Code=11 Count=1 Pid=52227 Tid=52227 Action=saDebug(saCore) Name=SIGSEGV(Illegal error segment) 
[DnsThread]     [52227] Throws an unknown exception
[HttpClient]    [7]     Resolve [transcoder.xxx.stream]
[HttpClient]    [7]     Resolve [transcoder.xxx.stream]`

**Comment by marakew** [comment]
i think its issue inside qemu/wine which your are using
or you cpu too old

**Comment by pimboli** [comment]
ah thanks, indeed. 
I tested on a non VM and it works.
