### ISSUE TITLE
IFace also for output?

### ISSUE THREAD

**Issue by thehijacker** [marakew/AvProxy#8]
I have config like this:

```
<?xml version="1.0"?>
<AvProxy Ver="1">
<Input Url="udp://239.40.1.1:3000?IFace=172.17.1.1">
    <Output Name="Test" Pnr=10>
            <TsPush Url="udp://238.1.1.1:5000?IFace=172.17.1.1"/>
    </Output>
</Input>
</AvProxy>
```

Input is a MPTS and I wish to filter only Pnr 10 on output on multicast 238.1.1.1:5000 but over specific interface. While it receives the multicast on correct defined IFace it doesn't use th IFace parameter on output. It this even and option?

**Comment by marakew** [comment]
IFace only for receives

i will look to improve and add IFace for output

**Comment by marakew** [comment]
could you try new version ?
i hope your are use AvProxy-x64 under linux

**Comment by zzlnewair** [comment]
The new version has no Audio Stream   only has video Stream , the old version is OK。

**Comment by marakew** [comment]
only AAC audio can pass
show me the log trace
